In [34]:
courses = ['History', 'Math', 'Physics', 'ComSci', 'Russian', 'French', 'English']

index = 4

while index > len(courses)-5 :
    print(courses[index])
    index += 1

    
print("\nNumber of elements is", len(courses))

Russian
French
English


IndexError: list index out of range

In [49]:
numbers = [0] * 5

print(numbers)

index = 0
while index < len(numbers):
    numbers[index]=1
    index += 2
    
print('\n')   

print(numbers)

[0, 0, 0, 0, 0]


[1, 0, 1, 0, 1]


In [69]:
#sales 


num_days = 5

sales = [0] * num_days
    
index = 0
weekday = 1
        
while index < len(sales):
        sales[index] = input("Please enter sale for  " + str(weekday) + " ")
        index += 1
        weekday += 1
print(sales)
   

Please enter sale for  1 54
Please enter sale for  2 45
Please enter sale for  3 65
Please enter sale for  4 32
Please enter sale for  5 64
['54', '45', '65', '32', '64']


Slicing and dicing (2)
In the video, Filip first discussed the syntax where you specify both where to begin and end the slice of your list:

my_list[begin:end]
However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:

x = ["a", "b", "c", "d"]
x[:2]
x[2:]
x[:]

Instructions

Create downstairs again, as the first 6 elements of areas. This time, simplify the slicing by omitting the begin index.
Create upstairs again, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.

In [76]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs

downstairs = areas[:]

# Alternative slicing to create upstairs


In [74]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area

eat_sleep_area = areas[-3] + areas[3]

print(eat_sleep_area)

# Print the variable eat_sleep_area


28.75


Slicing and dicing (2)
In the video, Filip first discussed the syntax where you specify both where to begin and end the slice of your list:

my_list[begin:end]
However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:

x = ["a", "b", "c", "d"]
x[:2]
x[2:]
x[:]

- Create downstairs again, as the first 6 elements of areas. This time, simplify the slicing by omitting the begin index.
- Create upstairs again, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.

In [1]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[-4:]

Subsetting lists of lists
You saw before that a Python list can contain practically anything; 
even other lists! To subset lists of lists, you can use the same technique as before: square brackets. 
Try out the commands in the following code sample in the IPython Shell:

x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
     
x[2][0]
x[2][:2]
x[2] results in a list, that you can subset again by adding additional square brackets.

What will house[-1][1] return? house, the list of lists that you created before, is already defined for you in the workspace. You can experiment with it in the IPython Shell.

In [2]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
print(x[2][0])  # [g]
print(x[2][:2]) # [g, h]

g
['g', 'h']


**Replace list elements**

Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?

x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]

For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

1. Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
2. Make the areas list more trendy! Change "living room" to "chill zone".

In [31]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]

print(x)b

['a', 'r', 's', 't']


In [32]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


## Extend a list

If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:

``` x = ["a", "b", "c", "d"]
y = x + ["e", "f"] ```



You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?

Instructions

- Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1.
- urther extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2.

In [38]:
x = ["a", "b", "c", "d"]
y =  ["e", "f"] +  x #order means everything

print(y)

['e', 'f', 'a', 'b', 'c', 'd']


In [39]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]


# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

## Delete list elements

Finally, you can also remove elements from your list. You can do this with the `del` statement:

```x = ["a", "b", "c", "d"]
del(x[1])```

Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!

The updated and extended version of `areas` that you've built in the previous exercises is coded below. You can copy and paste this into the IPython Shell to play around with the result.
```
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]```
         
There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the `areas` list.

The `;` sign is used to place commands on the same line. The following two code chunks are equivalent:
```
command1; command2


command1
command2```

Which of the code chunks will do the job for us?

Instructions

Possible Answers
- del(areas[10]); del(areas[11])
- del(areas[10:11])
- del(areas[-4:-2]) - Right answer
- del(areas[-3]); del(areas[-4])

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

del(areas)

In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

In [1]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

b = areas * 5

b

[11.25,
 18.0,
 20.0,
 10.75,
 9.5,
 11.25,
 18.0,
 20.0,
 10.75,
 9.5,
 11.25,
 18.0,
 20.0,
 10.75,
 9.5,
 11.25,
 18.0,
 20.0,
 10.75,
 9.5,
 11.25,
 18.0,
 20.0,
 10.75,
 9.5]

In [15]:
fam = [1.732341, 1.68, 1.71, 1.89, 'edmond', 1.71, 1.71, 'edmond','edmond', 'edmond']

y = 1.71
x = fam.count(y)

sum = x * y

print(x)
print(sum)

3
5.13


In [55]:
sister = 'liz'

sisternew = sister.replace('z','sa')

sisternew.capitalize()

'Lisa'

In [59]:
help(sorted)


Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [17]:
?str

In [40]:
fam = [1.732341, 1.68, 1.71, 1.89, 'edmond', 1.71, 1.71, 'edmond','edmond', 'edmond']

fam[-1] = fam[-1].upper()

fam.clear()

fam

[]

In [29]:
help(append)

NameError: name 'append' is not defined

In [32]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas[-1].remove()


# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

AttributeError: 'float' object has no attribute 'remove'

In [55]:
import numpy as n

x = n.array([1,2,3])
y = n.array([5,3,8])

bmi = x + y

bmi

array([ 6,  5, 11])

In [15]:
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]

high = y > 5
y[high]

type(y)

numpy.ndarray

In [14]:
np.array([True, False , 2]) + np.array([3, 4, False])

array([4, 4, 2])

In [43]:
baseball = [[180, 78.4, 23, 63, 117, 90],
            [215, 102.7, 99, 87, 1, 44],
            [210, 98.5, 421, 217, 33, 96, 23, 45],
            [188, 75.2, 31, 88, 21, 34]]

import numpy as np

np_baseball = np.array(baseball)

print(np_baseball[2])

[210, 98.5, 421, 217, 33, 96, 23, 45]


In [83]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

np.histogram2d([2,2],np_mat)



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
import numpy as np
np_mat = np.array([['a', 'b'],
                   ['c', 'd'],
                   ['e', 'f']])


In [89]:
q = [17, 25, 42, 35, 47, 45]
sqr(q)

NameError: name 'sqr' is not defined

In [97]:
import numpy as np
z = np.array([[5, 9, 8], 
              [9, 0, 6]])
print(z[0:, 0:])

[[5 9 8]
 [9 0 6]]
